Now support for FULL release testing inside SLURM container (unit tests, integration tests, auto-instrument by adding prolog/epilog into slurm.conf, sbatch, srun, the works..)
$ utils/check-release --no-unit-tests EPMT-2.1.0.tgz
Testing release: EPMT-2.1.0.tgz
Staging area: /tmp/EPMT-release-test
Wiping clean staging area and recreating it..
copying epmt-installer and EPMT-2.1.0.tgz to staging area
'utils/epmt-installer' -> '/tmp/EPMT-release-test/epmt-installer'
'EPMT-2.1.0.tgz' -> '/tmp/EPMT-release-test/EPMT-2.1.0.tgz'
Changing directory to: /tmp/EPMT-release-test (staging area)
/tmp/EPMT-release-test
Running epmt-installer..
Using release: /tmp/EPMT-release-test/EPMT-2.1.0.tgz

Enter full path to an empty install directory [/tmp/EPMT-release-test/epmt-2.1.0]: Install directory: /tmp
/EPMT-release-test/epmt-2.1.0
Press ENTER to continue, Ctrl-C to abort: Extracting release..
Installing settings.py
Fixing paths in slurm scripts
EPMT 2.1.0

***********************************************************************
Installation successful.
EPMT 2.1.0 installed in: /tmp/EPMT-release-test/epmt-2.1.0

Please add /tmp/EPMT-release-test/epmt-2.1.0/epmt-install/epmt to PATH:

For Bash:
export PATH="/tmp/EPMT-release-test/epmt-2.1.0/epmt-install/epmt:$PATH"

Or, for C shell/tcsh:
setenv PATH "/tmp/EPMT-release-test/epmt-2.1.0/epmt-install/epmt:$PATH"
***********************************************************************

EPMT_PREFIX=/tmp/EPMT-release-test/epmt-2.1.0
epmt: /tmp/EPMT-release-test/epmt-2.1.0/epmt-install/epmt/epmt
EPMT 2.1.0

tarting SLURM test container..
9048e0390e1c303209450dda0e57ff8b18231dbb9b3bf77dc5714b0dcec61cb2

Installing tcsh..
EPMT 2.1.0
WARNING:epmtlib:No job name found, defaulting to unknown
settings.db_params = {'url': 'sqlite:////root/EPMT_DB.sqlite', 'echo': False}   Pass
settings.install_prefix = /tmp/EPMT-release-test/epmt-2.1.0/papiex-epmt-install/        Pass
settings.epmt_output_prefix = /tmp/epmt/        Pass
/proc/sys/kernel/perf_event_paranoid =  1       Pass
settings.papiex_options = PERF_COUNT_SW_CPU_CLOCK       Pass
epmt stage functionality        Pass
epmt run functionality  Pass

Testing sbatch with epmt-example.?sh
Submitted batch job 2
drwxr-xr-x root/root         0 2019-12-02 21:46 ./
-rw-r--r-- root/root       642 2019-12-02 21:46 ./ernie-collated-papiex-2-0.csv
-rw-r--r-- root/root      3291 2019-12-02 21:46 ./job_metadata
sbatch epmt-example.sh PASSED
Submitted batch job 3
drwxr-xr-x root/root         0 2019-12-02 21:46 ./
-rw-r--r-- root/root       646 2019-12-02 21:46 ./ernie-collated-papiex-3-0.csv
-rw-r--r-- root/root      3933 2019-12-02 21:46 ./job_metadata
sbatch epmt-example.csh PASSED

Testing srun --task-prolog/task-epilog                                                           [32/2302]
drwxr-xr-x root/root         0 2019-12-02 21:46 ./
-rw-r--r-- root/root      4791 2019-12-02 21:46 ./job_metadata
-rw-r--r-- root/root       666 2019-12-02 21:46 ./ernie-collated-papiex-4-0.csv
srun --task-prolog/task-epilog sleep 1 PASSED

Testing auto-instrumentation by adding prolog/epilog to slurm.conf
Submitted batch job 5
drwxr-xr-x root/root         0 2019-12-02 21:46 ./
-rw-r--r-- root/root      2235 2019-12-02 21:46 ./ernie-collated-papiex-5-0.csv
-rw-r--r-- root/root      4096 2019-12-02 21:46 ./job_metadata
sbatch with auto-instrument using prolog/epilog PASSED

Running integration tests (in SLURM container)
1..11
ok 1 epmt version
ok 2 epmt submit
ok 3 # skip epmt_concat -h
ok 4 # skip epmt_concat with valid input dir
ok 5 # skip epmt_concat with valid input files
ok 6 # skip epmt_concat with non-existent directory
ok 7 # skip epmt_concat with non-existent files
ok 8 # skip epmt_concat with corrupted csv
ok 9 no daemon running
ok 10 start epmt daemon
ok 11 stop epmt daemon

skipping unit tests as invoked with --no-unit-tests option

Stopping SLURM test container..

diff --git a/utils/check-release b/utils/check-release
--- a/utils/check-release
+++ b/utils/check-release
@@ -9,9 +9,37 @@
 
 STAGE="/tmp/EPMT-release-test"
 
+skip_unittests=0
+case $1 in
+  --no-unit-tests) skip_unittests=1; shift;;
+  --help|help|-h|--h) echo "usage: check-release [--no-unit-tests] [/path/to/EPMT-*.tgz]"; exit 0;;
+esac
+
 function die() {
   echo $* >&2
   exit 1
+}
+
+wait_file() {
+  local file="$1"; shift
+  local wait_seconds="${1:-10}"; shift # 10 seconds as default timeout
+
+  until test $((wait_seconds--)) -eq 0 -o -f "$file" ; do sleep 1; done
+
+  ((++wait_seconds))
+}
+
+verify_staged_file() {
+  local tgz="$1"
+  local cmd="$2"
+  wait_file $tgz 10 || die "$tgz not found"
+  test -f $tgz && test -s $tgz
+  tar tvf $tgz
+  tar xf $tgz
+  test -s job_metadata
+  test -s *-collated-papiex-*-*.csv
+  rm -f job_metadata *-collated-papiex-*-*.csv
+  echo "$cmd PASSED"
 }
 
 release=${1:-$(ls -1rt EPMT-*.tgz| tail -n1)}
@@ -36,17 +64,51 @@ echo "Running epmt-installer.."
 echo -e "\n\n" | ./epmt-installer "$release_file"
 EPMT_PREFIX=$(ls -d /tmp/EPMT-release-test/epmt-*|grep -v installer)
 echo "EPMT_PREFIX=$EPMT_PREFIX"
-echo "Prepending $EPMT_PREFIX/epmt-install/epmt to PATH"
+# echo "Prepending $EPMT_PREFIX/epmt-install/epmt to PATH"
 export PATH="$EPMT_PREFIX/epmt-install/epmt:$PATH"
 echo "epmt: $(which epmt)"
 epmt -V
 
-echo "Running epmt check"
-epmt check
-rm -f db.sqlite
+# cleanup on exit or interrupt
+function cleanup() {
+  echo;echo "Stopping SLURM test container.."
+  docker stop centos7-slurm-release-test
+}
 
-echo;echo "Running integration tests"
-(cd $EPMT_PREFIX/epmt-install/epmt; test/integration/run_integration; rm -f db.sqlite)
+echo;echo "Starting SLURM test container.."
+trap cleanup EXIT INT QUIT HUP TERM
+docker run --name centos7-slurm-release-test --rm -dt -h ernie -v $PWD:$PWD:z -w $PWD --privileged -e PATH="$EPMT_PREFIX/epmt-install/epmt:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin" giovtorres/docker-centos7-slurm:19.05.1 tail -f /dev/null
+sleep 2
+echo;echo "Installing tcsh.."; docker exec centos7-slurm-release-test yum install -y -q tcsh
+docker exec centos7-slurm-release-test epmt -V
+docker exec centos7-slurm-release-test epmt check
 
-echo;echo "Running unit tests"
-epmt unittest; rm -f db.sqlite
+echo;echo "Testing sbatch with epmt-example.?sh"
+docker exec centos7-slurm-release-test sbatch "$EPMT_PREFIX/epmt-install/epmt/epmt-example.sh"
+verify_staged_file 2.tgz "sbatch epmt-example.sh"
+docker exec centos7-slurm-release-test sbatch "$EPMT_PREFIX/epmt-install/epmt/epmt-example.csh"
+verify_staged_file 3.tgz "sbatch epmt-example.csh"
+
+echo;echo "Testing srun --task-prolog/task-epilog"
+docker exec centos7-slurm-release-test srun -n1 --task-prolog="$EPMT_PREFIX/epmt-install/slurm/slurm_task_prolog_epmt.sh" --task-epilog="$EPMT_PREFIX/epmt-install/slurm/slurm_task_epilog_epmt.sh" sleep 1
+verify_staged_file 4.tgz "srun --task-prolog/task-epilog sleep 1"
+
+echo;echo "Testing auto-instrumentation by adding prolog/epilog to slurm.conf"
+docker exec centos7-slurm-release-test bash -c "echo TaskProlog=$EPMT_PREFIX/epmt-install/slurm/slurm_task_prolog_epmt.sh >> /etc/slurm/slurm.conf"
+docker exec centos7-slurm-release-test bash -c "echo TaskEpilog=$EPMT_PREFIX/epmt-install/slurm/slurm_task_epilog_epmt.sh >> /etc/slurm/slurm.conf"
+docker exec centos7-slurm-release-test scontrol reconfigure
+echo -e "#!/bin/tcsh\nsleep 1\n" > uninstr.csh
+docker exec centos7-slurm-release-test sbatch uninstr.csh
+verify_staged_file 5.tgz "sbatch with auto-instrument using prolog/epilog"
+
+echo;echo "Running integration tests (in SLURM container)"
+docker exec centos7-slurm-release-test bash -c "cd $EPMT_PREFIX/epmt-install/epmt; test/integration/run_integration"
+
+if [ $skip_unittests -eq 1 ]; then
+  echo;echo "skipping unit tests as invoked with --no-unit-tests option"
+else
+  echo;echo "Running unit tests (in SLURM container)"
+  docker exec centos7-slurm-release-test epmt unittest
+fi
+
+exit 0
