Add release name and os version to outputted tgz file. Note that OSX uses case-insensitive filesystems.

diff --git a/utils/mk-release b/utils/mk-release
--- a/utils/mk-release
+++ b/utils/mk-release
@@ -6,7 +6,8 @@ function die() {
 }
 
 version=$(grep VERSION Makefile| head -n 1| cut -f2 -d=); [ "$version" != "" ] || die "could not determine version"
-release_tar="EPMT-$version.tgz"
+target=$(grep OS_TARGET Makefile| head -n 1| cut -f2 -d=); [ "$target" != "" ] || die "could not determine target"
+release_tar="EPMT-release-$version-$target.tgz"
 
 [ ! -f $release_tar ] || die "Release file $release_tar already exists. Please remove it and try again"
 
@@ -16,7 +17,7 @@ case $1 in
 esac
 
 
-echo "Making EPMT release $version"
+echo "Making EPMT release $version for $target..."
 
 if [ $no_build -eq 0 ]; then
     echo " - building epmt and epmt-test tarball"
