Update build_and_test_epmt.yml

diff --git a/.github/workflows/build_and_test_epmt.yml b/.github/workflows/build_and_test_epmt.yml
--- a/.github/workflows/build_and_test_epmt.yml
+++ b/.github/workflows/build_and_test_epmt.yml
@@ -92,7 +92,7 @@ jobs:
       - name: epmt check call and check
         continue-on-error: true
         run: |
-          echo 2 > /proc/sys/kernel/perf_event_paranoid
+          echo 2 > /proc/sys/kernel/perf_event_paranoid || echo "failing this is understandable in CI"
           epmt -v check
 
       - name: epmt unittest call and check
